import type { ApprovalRequest } from "./types";

export const mockRequests: ApprovalRequest[] = [
  {
    id: "REQ-2026-001",
    title: "出差申請 - 台北客戶拜訪",
    type: "出差申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-18",
    amount: 12500,
    description: "拜訪台北客戶討論新專案需求，預計 4/25-4/26 兩天。交通費、住宿費及餐費預估 NT$12,500。",
    status: "pending",
    currentApprover: "王經理",
    approvers: [
      { order: 1, name: "李組長", role: "直屬主管", status: "approved", comment: "同意", actionDate: "2026-04-18" },
      { order: 2, name: "王經理", role: "部門經理", status: "pending" },
      { order: 3, name: "張副總", role: "副總經理", status: "pending" },
    ],
  },
  {
    id: "REQ-2026-002",
    title: "採購申請 - 開發用筆電",
    type: "採購申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-17",
    amount: 45000,
    description: "因原筆電效能不足影響開發效率，申請採購 MacBook Pro 一台，預算 NT$45,000。",
    status: "pending",
    currentApprover: "林廷軒",
    approvers: [
      { order: 1, name: "林廷軒", role: "直屬主管", status: "pending" },
      { order: 2, name: "王經理", role: "部門經理", status: "pending" },
    ],
  },
  {
    id: "REQ-2026-003",
    title: "請假申請 - 特休 2 天",
    type: "請假申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-16",
    description: "申請 4/28-4/29 特休兩天，處理私人事務。已安排代理人完成工作交接。",
    status: "approved",
    currentApprover: "",
    approvers: [
      { order: 1, name: "李組長", role: "直屬主管", status: "approved", comment: "准假", actionDate: "2026-04-16" },
      { order: 2, name: "王經理", role: "部門經理", status: "approved", comment: "同意", actionDate: "2026-04-17" },
    ],
  },
  {
    id: "REQ-2026-004",
    title: "加班申請 - 系統上線支援",
    type: "加班申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-15",
    description: "配合客戶系統上線，預計 4/20 加班至 22:00，約 4 小時。",
    status: "rejected",
    currentApprover: "",
    approvers: [
      { order: 1, name: "李組長", role: "直屬主管", status: "approved", comment: "同意", actionDate: "2026-04-15" },
      { order: 2, name: "王經理", role: "部門經理", status: "rejected", comment: "建議調整為調休方式處理", actionDate: "2026-04-16" },
    ],
  },
  {
    id: "REQ-2026-005",
    title: "費用報銷 - 客戶餐敘",
    type: "費用報銷",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-19",
    amount: 3200,
    description: "4/18 與客戶餐敘費用 NT$3,200，共 4 人。附發票。",
    status: "pending",
    currentApprover: "林廷軒",
    approvers: [
      { order: 1, name: "林廷軒", role: "直屬主管", status: "pending" },
    ],
  },
  {
    id: "REQ-2026-006",
    title: "採購申請 - 27 吋外接螢幕",
    type: "採購申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-19",
    amount: 8900,
    description: "申請採購 Dell 27 吋 4K 螢幕一台，提升開發效率。預算 NT$8,900。",
    status: "pending",
    currentApprover: "李組長",
    approvers: [
      { order: 1, name: "李組長", role: "直屬主管", status: "pending" },
      { order: 2, name: "王經理", role: "部門經理", status: "pending" },
    ],
  },
  {
    id: "REQ-2026-007",
    title: "出差申請 - 高雄技術研討會",
    type: "出差申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-20",
    amount: 6800,
    description: "參加 5/5 高雄 Azure 技術研討會，當日來回。高鐵票及餐費預估 NT$6,800。",
    status: "pending",
    currentApprover: "林廷軒",
    approvers: [
      { order: 1, name: "林廷軒", role: "直屬主管", status: "pending" },
      { order: 2, name: "王經理", role: "部門經理", status: "pending" },
    ],
  },
  {
    id: "REQ-2026-008",
    title: "請假申請 - 病假 1 天",
    type: "請假申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-14",
    description: "4/14 身體不適請病假一天，已通知同事代理。",
    status: "approved",
    currentApprover: "",
    approvers: [
      { order: 1, name: "李組長", role: "直屬主管", status: "approved", comment: "注意身體", actionDate: "2026-04-14" },
    ],
  },
  {
    id: "REQ-2026-009",
    title: "費用報銷 - 計程車費",
    type: "費用報銷",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-20",
    amount: 450,
    description: "4/19 加班至深夜搭計程車回家，車資 NT$450。附收據。",
    status: "pending",
    currentApprover: "林廷軒",
    approvers: [
      { order: 1, name: "林廷軒", role: "直屬主管", status: "pending" },
      { order: 2, name: "王經理", role: "部門經理", status: "pending" },
    ],
  },
  {
    id: "REQ-2026-010",
    title: "加班申請 - 專案趕工",
    type: "加班申請",
    applicant: "林廷軒",
    applicantEmail: "B11410001@pershing.com.tw",
    department: "雲端事業處",
    submitDate: "2026-04-13",
    description: "配合專案交付期限，4/13 加班至 21:00，約 3 小時。",
    status: "approved",
    currentApprover: "",
    approvers: [
      { order: 1, name: "李組長", role: "直屬主管", status: "approved", comment: "辛苦了", actionDate: "2026-04-13" },
      { order: 2, name: "王經理", role: "部門經理", status: "approved", comment: "同意", actionDate: "2026-04-14" },
    ],
  },
];
